[package]
name = "bit_field_derive"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
syn = "=0.15"
quote = "=0.6"
proc-macro2 = "=0.4"

[lib]
proc-macro = true
path = "bit_field_derive.rs"
