[package]
name = "cros_async"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
io_uring = { path = "../io_uring" }
libc = "*"
paste = "*"
pin-utils = "0.1.0-alpha.4"
sys_util = { path = "../sys_util" }
syscall_defines = { path = "../syscall_defines" }
vm_memory = { path = "../vm_memory" }

[dependencies.futures]
version = "*"
default-features = false
features = ["alloc"]

[dev-dependencies]
tempfile = { path = "../tempfile" }
