[package]
name = "hypervisor"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
bit_field = { path = "../bit_field" }
enumn = { path = "../enumn" }
libc = "*"
kvm = { path = "../kvm" }
kvm_sys = { path = "../kvm_sys" }
sync = { path = "../sync" }
sys_util = { path = "../sys_util" }
