[package]
name = "hypervisor"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
libc = "*"
kvm = { path = "../kvm" }
kvm_sys = { path = "../kvm_sys" }
sync = { path = "../sync" }
sys_util = { path = "../sys_util" }
