[package]
name = "vm_control"
version = "0.1.0"
authors = ["The Chromium OS Authors"]

[features]
sandboxed-libusb = []

[dependencies]
byteorder = "*"
data_model = { path = "../data_model" }
kvm = { path = "../kvm" }
libc = "*"
sys_util = { path = "../sys_util" }
resources = { path = "../resources" }
msg_socket = { path = "../msg_socket" }
