[package]
name = "crosvm_plugin"
version = "0.17.0"
authors = ["The Chromium OS Authors"]

[lib]
crate-type = ["cdylib"]

[dependencies]
protobuf = "=1.4.3"
plugin_proto = { path = "../plugin_proto" }
sys_util = { path = "../sys_util" }
kvm = { path = "../kvm" }
kvm_sys = { path = "../kvm_sys" }
libc = "*"
