[package]
name = "vhost_user_devices"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
base = { path = "../base" }
devices = { path = "../devices" }
libc = "*"
remain = "*"
sync = { path = "../sync" }
thiserror = "*"
vm_memory = { path = "../vm_memory" }
vmm_vhost = { version = "*", features = ["vhost-user-slave"] }

[dev-dependencies]
data_model = { path = "../data_model" }
tempfile = { path = "../tempfile" }
