[package]
name = "vhost_user_devices"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[[bin]]
name = "vhost-user-console-device"
path = "src/console_device.rs"

[[bin]]
name = "vhost-user-net-device"
path = "src/net_device.rs"

[[bin]]
name = "vhost-user-wl-device"
path = "src/wl_device.rs"

[[bin]]
name = "vhost-user-block-device"
path = "src/block_device.rs"

[dependencies]
anyhow = "*"
devices = { path = "../devices", features = ["minigbm"] }
