[package]
name = "libvda"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"
links = "vda"

[dependencies]
enumn = { path = "../common/enumn" }
libc = "*"

[build-dependencies]
pkg-config = "*"
