[package]
name = "crosvm-fuzz"
version = "0.0.1"
authors = ["The Chromium OS Authors"]

[dependencies]
libc = "*"
kernel_loader = { path = "../kernel_loader" }
sys_util = { path = "../sys_util" }

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "crosvm_zimage_fuzzer"
path = "zimage_fuzzer.rs"
