[package]
name = "devices"
version = "0.1.0"
authors = ["The Chromium OS Authors"]

[features]
wl-dmabuf = []
gpu = ["gpu_buffer", "gpu_display", "gpu_renderer"]
tpm = ["tpm2"]

[dependencies]
audio_streams = "*"
bit_field = { path = "../bit_field" }
byteorder = "*"
data_model = { path = "../data_model" }
gpu_buffer = { path = "../gpu_buffer", optional = true }
gpu_display = { path = "../gpu_display", optional = true }
gpu_renderer = { path = "../gpu_renderer", optional = true }
enumn = { path = "../enumn" }
kvm = { path = "../kvm" }
libc = "*"
io_jail = { path = "../io_jail" }
msg_on_socket_derive = { path = "../msg_socket/msg_on_socket_derive" }
msg_socket = { path = "../msg_socket" }
net_sys = { path = "../net_sys" }
net_util = { path = "../net_util" }
p9 = { path = "../p9" }
resources = { path = "../resources" }
sync = { path = "../sync" }
sys_util = { path = "../sys_util" }
tpm2 = { path = "../tpm2", optional = true }
usb_util = { path = "../usb_util" }
vhost = { path = "../vhost" }
virtio_sys = { path = "../virtio_sys" }
vm_control = { path = "../vm_control" }
