[package]
name = "io_uring"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2021"

[dependencies]
data_model = { path = "../common/data_model" } # provided by ebuild
libc = "0.2.93"
remain = "0.2"
sync = { path = "../common/sync" } # provided by ebuild
sys_util = { path = "../common/sys_util" } # provided by ebuild
thiserror = "1"

[dev-dependencies]
tempfile = "3"


