[package]
name = "poll_token_derive"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"
include = ["*.rs", "Cargo.toml"]

[lib]
proc-macro = true
path = "poll_token_derive.rs"

[dependencies]
syn = "0.15"
quote = "0.6"
proc-macro2 = "0.4"
